// Gen 5 moves
#define MOVE_HONE_CLAWS   471
#define MOVE_WIDE_GUARD   472
#define MOVE_GUARD_SPLIT  473
#define MOVE_POWER_SPLIT  474
#define MOVE_WONDER_ROOM  475
#define MOVE_PSYSHOCK     476
#define MOVE_VENOSHOCK    477
#define MOVE_AUTOTOMIZE   478
#define MOVE_RAGE_POWDER  479
#define MOVE_TELEKINESIS  480
#define MOVE_MAGIC_ROOM   481
#define MOVE_SMACK_DOWN   482
#define MOVE_STORM_THROW  483
#define MOVE_FLAME_BURST  484
#define MOVE_SLUDGE_WAVE  485
#define MOVE_QUIVER_DANCE 486
#define MOVE_HEAVY_SLAM   487
#define MOVE_SYNCHRONOISE 488
#define MOVE_ELECTRO_BALL 489
#define MOVE_SOAK         490
#define MOVE_FLAME_CHARGE 491
#define MOVE_COIL         492
#define MOVE_LOW_SWEEP    493
#define MOVE_ACID_SPRAY   494
#define MOVE_FOUL_PLAY    495
#define MOVE_SIMPLE_BEAM  496
#define MOVE_ENTRAINMENT  497
#define MOVE_AFTER_YOU    498
#define MOVE_ROUND        499
#define MOVE_ECHOED_VOICE 500
#define MOVE_CHIP_AWAY    501
#define MOVE_CLEAR_SMOG   502
#define MOVE_STORED_POWER 503
#define MOVE_QUICK_GUARD  504
#define MOVE_ALLY_SWITCH  505
#define MOVE_SCALD        506
#define MOVE_SHELL_SMASH  507
#define MOVE_HEAL_PULSE   508
#define MOVE_HEX          509
#define MOVE_SKY_DROP     510
#define MOVE_SHIFT_GEAR   511
#define MOVE_CIRCLE_THROW 512
#define MOVE_INCINERATE   513
#define MOVE_QUASH        514
#define MOVE_ACROBATICS   515
#define MOVE_REFLECT_TYPE 516
#define MOVE_RETALIATE    517
#define MOVE_FINAL_GAMBIT 518
#define MOVE_BESTOW       519
#define MOVE_INFERNO      520
#define MOVE_WATER_PLEDGE 521
#define MOVE_FIRE_PLEDGE  522
#define MOVE_GRASS_PLEDGE 523
#define MOVE_VOLT_SWITCH  524
#define MOVE_STRUGGLE_BUG 525
#define MOVE_BULLDOZE     526
#define MOVE_FROST_BREATH 527
#define MOVE_DRAGON_TAIL  528
#define MOVE_WORK_UP      529
#define MOVE_ELECTROWEB   530
#define MOVE_WILD_CHARGE  531
#define MOVE_DRILL_RUN    532
#define MOVE_DUAL_CHOP    533
#define MOVE_HEART_STAMP  534
#define MOVE_HORN_LEECH   535
#define MOVE_SACRED_SWORD 536
#define MOVE_RAZOR_SHELL  537
#define MOVE_HEAT_CRASH   538
#define MOVE_LEAF_TORNADO 539
#define MOVE_STEAMROLLER  540
#define MOVE_COTTON_GUARD 541
#define MOVE_NIGHT_DAZE   542
#define MOVE_PSYSTRIKE    543
#define MOVE_TAIL_SLAP    544
#define MOVE_HURRICANE    545
#define MOVE_HEAD_CHARGE  546
#define MOVE_GEAR_GRIND   547
#define MOVE_SEARING_SHOT 548
#define MOVE_TECHNO_BLAST 549
#define MOVE_RELIC_SONG   550
#define MOVE_SECRET_SWORD 551
#define MOVE_GLACIATE     552
#define MOVE_BOLT_STRIKE  553
#define MOVE_BLUE_FLARE   554
#define MOVE_FIERY_DANCE  555
#define MOVE_FREEZE_SHOCK 556
#define MOVE_ICE_BURN     557
#define MOVE_SNARL        558
#define MOVE_ICICLE_CRASH 559
#define MOVE_V_CREATE     560
#define MOVE_FUSION_FLARE 561
#define MOVE_FUSION_BOLT  562
// Gen 6 moves.
#define MOVE_FLYING_PRESS     563
#define MOVE_MAT_BLOCK        564
#define MOVE_BELCH            565
#define MOVE_ROTOTILLER       566
#define MOVE_STICKY_WEB       567
#define MOVE_FELL_STINGER     568
#define MOVE_PHANTOM_FORCE    569
#define MOVE_TRICK_OR_TREAT   570
#define MOVE_NOBLE_ROAR       571
#define MOVE_ION_DELUGE       572
#define MOVE_PARABOLIC_CHARGE 573
#define MOVE_FORESTS_CURSE    574
#define MOVE_PETAL_BLIZZARD   575
#define MOVE_FREEZE_DRY       576
#define MOVE_DISARMING_VOICE  577
#define MOVE_PARTING_SHOT     578
#define MOVE_TOPSY_TURVY      579
#define MOVE_DRAINING_KISS    580
#define MOVE_CRAFTY_SHIELD    581
#define MOVE_FLOWER_SHIELD    582
#define MOVE_GRASSY_TERRAIN   583
#define MOVE_MISTY_TERRAIN    584
#define MOVE_ELECTRIFY        585
#define MOVE_PLAY_ROUGH       586
#define MOVE_FAIRY_WIND       587
#define MOVE_MOONBLAST        588
#define MOVE_BOOMBURST        589
#define MOVE_FAIRY_LOCK       590
#define MOVE_KINGS_SHIELD     591
#define MOVE_PLAY_NICE        592
#define MOVE_CONFIDE          593
#define MOVE_DIAMOND_STORM    594
#define MOVE_STEAM_ERUPTION   595
#define MOVE_HYPERSPACE_HOLE  596
#define MOVE_WATER_SHURIKEN   597
#define MOVE_MYSTICAL_FIRE    598
#define MOVE_SPIKY_SHIELD     599
#define MOVE_AROMATIC_MIST    600
#define MOVE_EERIE_IMPULSE    601
#define MOVE_VENOM_DRENCH     602
#define MOVE_POWDER           603
#define MOVE_GEOMANCY         604
#define MOVE_MAGNETIC_FLUX    605
#define MOVE_HAPPY_HOUR       606
#define MOVE_ELECTRIC_TERRAIN 607
#define MOVE_DAZZLING_GLEAM   608
#define MOVE_CELEBRATE        609
#define MOVE_HOLD_HANDS       610
#define MOVE_BABY_DOLL_EYES   611
#define MOVE_NUZZLE           612
#define MOVE_HOLD_BACK        613
#define MOVE_INFESTATION      614
#define MOVE_POWER_UP_PUNCH   615
#define MOVE_OBLIVION_WING    616
#define MOVE_THOUSAND_ARROWS  617
#define MOVE_THOUSAND_WAVES   618
#define MOVE_LANDS_WRATH      619
#define MOVE_LIGHT_OF_RUIN    620
#define MOVE_ORIGIN_PULSE     621
#define MOVE_PRECIPICE_BLADES 622
#define MOVE_DRAGON_ASCENT    623
#define MOVE_HYPERSPACE_FURY  624
// Gen 7 moves.
#define MOVE_BREAKNECK_BLITZ_PHYSICAL        625
#define MOVE_BREAKNECK_BLITZ_SPECIAL         626
#define MOVE_ALL_OUT_PUMMELING_PHYSICAL      627
#define MOVE_ALL_OUT_PUMMELING_SPECIAL       628
#define MOVE_SUPERSONIC_SKYSTRIKE_PHYSICAL   629
#define MOVE_SUPERSONIC_SKYSTRIKE_SPECIAL    630
#define MOVE_ACID_DOWNPOUR_PHYSICAL          631
#define MOVE_ACID_DOWNPOUR_SPECIAL           632
#define MOVE_TECTONIC_RAGE_PHYSICAL          633
#define MOVE_TECTONIC_RAGE_SPECIAL           634
#define MOVE_CONTINENTAL_CRUSH_PHYSICAL      635
#define MOVE_CONTINENTAL_CRUSH_SPECIAL       636
#define MOVE_SAVAGE_SPIN_OUT_PHYSICAL        637
#define MOVE_SAVAGE_SPIN_OUT_SPECIAL         638
#define MOVE_NEVER_ENDING_NIGHTMARE_PHYSICAL 639
#define MOVE_NEVER_ENDING_NIGHTMARE_SPECIAL  640
#define MOVE_CORKSCREW_CRASH_PHYSICAL        641
#define MOVE_CORKSCREW_CRASH_SPECIAL         642
#define MOVE_INFERNO_OVERDRIVE_PHYSICAL      643
#define MOVE_INFERNO_OVERDRIVE_SPECIAL       644
#define MOVE_HYDRO_VORTEX_PHYSICAL           645
#define MOVE_HYDRO_VORTEX_SPECIAL            646
#define MOVE_BLOOM_DOOM_PHYSICAL             647
#define MOVE_BLOOM_DOOM_SPECIAL              648
#define MOVE_GIGAVOLT_HAVOC_PHYSICAL         649
#define MOVE_GIGAVOLT_HAVOC_SPECIAL          650
#define MOVE_SHATTERED_PSYCHE_PHYSICAL       651
#define MOVE_SHATTERED_PSYCHE_SPECIAL        652
#define MOVE_SUBZERO_SLAMMER_PHYSICAL        653
#define MOVE_SUBZERO_SLAMMER_SPECIAL         654
#define MOVE_DEVASTATING_DRAKE_PHYSICAL      655
#define MOVE_DEVASTATING_DRAKE_SPECIAL       656
#define MOVE_BLACK_HOLE_ECLIPSE_PHYSICAL     657
#define MOVE_BLACK_HOLE_ECLIPSE_SPECIAL      658
#define MOVE_TWINKLE_TACKLE_PHYSICAL         659
#define MOVE_TWINKLE_TACKLE_SPECIAL          660
#define MOVE_CATASTROPIKA                    661
#define MOVE_SHORE_UP                        662
#define MOVE_FIRST_IMPRESSION                663
#define MOVE_BANEFUL_BUNKER                  664
#define MOVE_SPIRIT_SHACKLE                  665
#define MOVE_DARKEST_LARIAT                  666
#define MOVE_SPARKLING_ARIA                  667
#define MOVE_ICE_HAMMER                      668
#define MOVE_FLORAL_HEALING                  669
#define MOVE_HIGH_HORSEPOWER                 670
#define MOVE_STRENGTH_SAP                    671
#define MOVE_SOLAR_BLADE                     672
#define MOVE_LEAFAGE                         673
#define MOVE_SPOTLIGHT                       674
#define MOVE_TOXIC_THREAD                    675
#define MOVE_LASER_FOCUS                     676
#define MOVE_GEAR_UP                         677
#define MOVE_THROAT_CHOP                     678
#define MOVE_POLLEN_PUFF                     679
#define MOVE_ANCHOR_SHOT                     680
#define MOVE_PSYCHIC_TERRAIN                 681
#define MOVE_LUNGE                           682
#define MOVE_FIRE_LASH                       683
#define MOVE_POWER_TRIP                      684
#define MOVE_BURN_UP                         685
#define MOVE_SPEED_SWAP                      686
#define MOVE_SMART_STRIKE                    687
#define MOVE_PURIFY                          688
#define MOVE_REVELATION_DANCE                689
#define MOVE_CORE_ENFORCER                   690
#define MOVE_TROP_KICK                       691
#define MOVE_INSTRUCT                        692
#define MOVE_BEAK_BLAST                      693
#define MOVE_CLANGING_SCALES                 694
#define MOVE_DRAGON_HAMMER                   695
#define MOVE_BRUTAL_SWING                    696
#define MOVE_AURORA_VEIL                     697
#define MOVE_SINISTER_ARROW_RAID             698
#define MOVE_MALICIOUS_MOONSAULT             699
#define MOVE_OCEANIC_OPERETTA                700
#define MOVE_GUARDIAN_OF_ALOLA               701
#define MOVE_SOUL_STEALING_7_STAR_STRIKE     702
#define MOVE_STOKED_SPARKSURFER              703
#define MOVE_PULVERIZING_PANCAKE             704
#define MOVE_EXTREME_EVOBOOST                705
#define MOVE_GENESIS_SUPERNOVA               706
#define MOVE_SHELL_TRAP                      707
#define MOVE_FLEUR_CANNON                    708
#define MOVE_PSYCHIC_FANGS                   709
#define MOVE_STOMPING_TANTRUM                710
#define MOVE_SHADOW_BONE                     711
#define MOVE_ACCELEROCK                      712
#define MOVE_LIQUIDATION                     713
#define MOVE_PRISMATIC_LASER                 714
#define MOVE_SPECTRAL_THIEF                  715
#define MOVE_SUNSTEEL_STRIKE                 716
#define MOVE_MOONGEIST_BEAM                  717
#define MOVE_TEARFUL_LOOK                    718
#define MOVE_ZING_ZAP                        719
#define MOVE_NATURES_MADNESS                 720
#define MOVE_MULTI_ATTACK                    721
#define MOVE_10_000_000_VOLT_THUNDERBOLT     722
#define MOVE_MIND_BLOWN                      723
#define MOVE_PLASMA_FISTS                    724
#define MOVE_PHOTON_GEYSER                   725
#define MOVE_LIGHT_THAT_BURNS_THE_SKY        726
#define MOVE_SEARING_SUNRAZE_SMASH           727
#define MOVE_MENACING_MOONRAZE_MAELSTROM     728
#define MOVE_LETS_SNUGGLE_FOREVER            729
#define MOVE_SPLINTERED_STORMSHARDS          730
#define MOVE_CLANGOROUS_SOULBLAZE            731
#define MOVE_ZIPPY_ZAP                       732
#define MOVE_SPLISHY_SPLASH                  733
#define MOVE_FLOATY_FALL                     734
#define MOVE_PIKA_PAPOW                      735
#define MOVE_BOUNCY_BUBBLE                   736
#define MOVE_BUZZY_BUZZ                      737
#define MOVE_SIZZLY_SLIDE                    738
#define MOVE_GLITZY_GLOW                     739
#define MOVE_BADDY_BAD                       740
#define MOVE_SAPPY_SEED                      741
#define MOVE_FREEZY_FROST                    742
#define MOVE_SPARKLY_SWIRL                   743
#define MOVE_VEEVEE_VOLLEY                   744
#define MOVE_DOUBLE_IRON_BASH                745
// Gen 8 moves.
#define MOVE_MAX_GUARD        746
#define MOVE_DYNAMAX_CANNON   747
#define MOVE_SNIPE_SHOT       748
#define MOVE_JAW_LOCK         749
#define MOVE_STUFF_CHEEKS     750
#define MOVE_NO_RETREAT       751
#define MOVE_TAR_SHOT         752
#define MOVE_MAGIC_POWDER     753
#define MOVE_DRAGON_DARTS     754
#define MOVE_TEATIME          755
#define MOVE_OCTOLOCK         756
#define MOVE_BOLT_BEAK        757
#define MOVE_FISHIOUS_REND    758
#define MOVE_COURT_CHANGE     759
#define MOVE_MAX_FLARE        760
#define MOVE_MAX_FLUTTERBY    761
#define MOVE_MAX_LIGHTNING    762
#define MOVE_MAX_STRIKE       763
#define MOVE_MAX_KNUCKLE      764
#define MOVE_MAX_PHANTASM     765
#define MOVE_MAX_HAILSTORM    766
#define MOVE_MAX_OOZE         767
#define MOVE_MAX_GEYSER       768
#define MOVE_MAX_AIRSTREAM    769
#define MOVE_MAX_STARFALL     770
#define MOVE_MAX_WYRMWIND     771
#define MOVE_MAX_MINDSTORM    772
#define MOVE_MAX_ROCKFALL     773
#define MOVE_MAX_QUAKE        774
#define MOVE_MAX_DARKNESS     775
#define MOVE_MAX_OVERGROWTH   776
#define MOVE_MAX_STEELSPIKE   777
#define MOVE_CLANGOROUS_SOUL  778
#define MOVE_BODY_PRESS       779
#define MOVE_DECORATE         780
#define MOVE_DRUM_BEATING     781
#define MOVE_SNAP_TRAP        782
#define MOVE_PYRO_BALL        783
#define MOVE_BEHEMOTH_BLADE   784
#define MOVE_BEHEMOTH_BASH    785
#define MOVE_AURA_WHEEL       786
#define MOVE_BREAKING_SWIPE   787
#define MOVE_BRANCH_POKE      788
#define MOVE_OVERDRIVE        789
#define MOVE_APPLE_ACID       790
#define MOVE_GRAV_APPLE       791
#define MOVE_SPIRIT_BREAK     792
#define MOVE_STRANGE_STEAM    793
#define MOVE_LIFE_DEW         794
#define MOVE_OBSTRUCT         795
#define MOVE_FALSE_SURRENDER  796
#define MOVE_METEOR_ASSAULT   797
#define MOVE_ETERNABEAM       798
#define MOVE_STEEL_BEAM       799
#define MOVE_EXPANDING_FORCE  800
#define MOVE_STEEL_ROLLER     801
#define MOVE_SCALE_SHOT       802
#define MOVE_METEOR_BEAM      803
#define MOVE_SHELL_SIDE_ARM   804
#define MOVE_MISTY_EXPLOSION  805
#define MOVE_GRASSY_GLIDE     806
#define MOVE_RISING_VOLTAGE   807
#define MOVE_TERRAIN_PULSE    808
#define MOVE_SKITTER_SMACK    809
#define MOVE_BURNING_JEALOUSY 810
#define MOVE_LASH_OUT         811
#define MOVE_POLTERGEIST      812
#define MOVE_CORROSIVE_GAS    813
#define MOVE_COACHING         814
#define MOVE_FLIP_TURN        815
#define MOVE_TRIPLE_AXEL      816
#define MOVE_DUAL_WINGBEAT    817
#define MOVE_SCORCHING_SANDS  818
#define MOVE_JUNGLE_HEALING   819
#define MOVE_WICKED_BLOW      820
#define MOVE_SURGING_STRIKES  821
#define MOVE_THUNDER_CAGE     822
#define MOVE_DRAGON_ENERGY    823
#define MOVE_FREEZING_GLARE   824
#define MOVE_FIERY_WRATH      825
#define MOVE_THUNDEROUS_KICK  826
#define MOVE_GLACIAL_LANCE    827
#define MOVE_ASTRAL_BARRAGE   828
#define MOVE_EERIE_SPELL      829
#define MOVE_DIRE_CLAW        830
#define MOVE_PSYSHIELD_BASH   831
#define MOVE_POWER_SHIFT      832
#define MOVE_STONE_AXE        833
#define MOVE_SPRINGTIDE_STORM 834
#define MOVE_MYSTICAL_POWER   835
#define MOVE_RAGING_FURY      836
#define MOVE_WAVE_CRASH       837
#define MOVE_CHLOROBLAST      838
#define MOVE_MOUNTAIN_GALE    839
#define MOVE_VICTORY_DANCE    840
#define MOVE_HEADLONG_RUSH    841
#define MOVE_BARB_BARRAGE     842
#define MOVE_ESPER_WING       843
#define MOVE_BITTER_MALICE    844
#define MOVE_SHELTER          845
#define MOVE_TRIPLE_ARROWS    846
#define MOVE_INFERNAL_PARADE  847
#define MOVE_CEASELESS_EDGE   848
#define MOVE_BLEAKWIND_STORM  849
#define MOVE_WILDBOLT_STORM   850
#define MOVE_SANDSEAR_STORM   851
#define MOVE_LUNAR_BLESSING   852
#define MOVE_TAKE_HEART       853
// Gen 9 moves.
#define MOVE_TERA_BLAST       854
#define MOVE_SILK_TRAP        855
#define MOVE_AXE_KICK         856
#define MOVE_LAST_RESPECTS    857
#define MOVE_LUMINA_CRASH     858
#define MOVE_ORDER_UP         859
#define MOVE_JET_PUNCH        860
#define MOVE_SPICY_EXTRACT    861
#define MOVE_SPIN_OUT         862
#define MOVE_POPULATION_BOMB  863
#define MOVE_ICE_SPINNER      864
#define MOVE_GLAIVE_RUSH      865
#define MOVE_REVIVAL_BLESSING 866
#define MOVE_SALT_CURE        867
#define MOVE_TRIPLE_DIVE      868
#define MOVE_MORTAL_SPIN      869
#define MOVE_DOODLE           870
#define MOVE_FILLET_AWAY      871
#define MOVE_KOWTOW_CLEAVE    872
#define MOVE_FLOWER_TRICK     873
#define MOVE_TORCH_SONG       874
#define MOVE_AQUA_STEP        875
#define MOVE_RAGING_BULL      876
#define MOVE_MAKE_IT_RAIN     877
#define MOVE_PSYBLADE         878
#define MOVE_HYDRO_STEAM      879
#define MOVE_RUINATION        880
#define MOVE_COLLISION_COURSE 881
#define MOVE_ELECTRO_DRIFT    882
#define MOVE_SHED_TAIL        883
#define MOVE_CHILLY_RECEPTION 884
#define MOVE_TIDY_UP          885
#define MOVE_SNOWSCAPE        886
#define MOVE_POUNCE           887
#define MOVE_TRAILBLAZE       888
#define MOVE_CHILLING_WATER   889
#define MOVE_HYPER_DRILL      890
#define MOVE_TWIN_BEAM        891
#define MOVE_RAGE_FIST        892
#define MOVE_ARMOR_CANNON     893
#define MOVE_BITTER_BLADE     894
#define MOVE_DOUBLE_SHOCK     895
#define MOVE_GIGATON_HAMMER   896
#define MOVE_COMEUPPANCE      897
#define MOVE_AQUA_CUTTER      898
#define MOVE_BLAZING_TORQUE   899
#define MOVE_WICKED_TORQUE    900
#define MOVE_NOXIOUS_TORQUE   901
#define MOVE_COMBAT_TORQUE    902
#define MOVE_MAGICAL_TORQUE   903
#define MOVE_BLOOD_MOON       904
#define MOVE_MATCHA_GOTCHA    905
#define MOVE_SYRUP_BOMB       906
#define MOVE_IVY_CUDGEL       907
#define MOVE_ELECTRO_SHOT     908
#define MOVE_TERA_STARSTORM   909
#define MOVE_FICKLE_BEAM      910
#define MOVE_BURNING_BULWARK  911
#define MOVE_THUNDERCLAP      912
#define MOVE_MIGHTY_CLEAVE    913
#define MOVE_TACHYON_CUTTER   914
#define MOVE_HARD_PRESS       915
#define MOVE_DRAGON_CHEER     916
#define MOVE_ALLURING_VOICE   917
#define MOVE_TEMPER_FLARE     918
#define MOVE_SUPERCELL_SLAM   919
#define MOVE_PSYCHIC_NOISE    920
#define MOVE_UPPER_HAND       921
#define MOVE_MALIGNANT_CHAIN  922
